D: https://arstechnica.com
D: https://arstechnica.com /cgi-bin/
D: https://arstechnica.com /wp/wp-admin/
D: https://arstechnica.com /wp/wp-includes/
D: https://arstechnica.com /wp/wp-content/
D: https://arstechnica.com /wp-content/plugins/
D: https://arstechnica.com /wp-content/mu_plugins/
D: https://arstechnica.com /wp-content/cache/
D: https://arstechnica.com /wp-content/themes/
D: https://arstechnica.com /trackback/
D: https://arstechnica.com /comments/
D: https://arstechnica.com /category/*/*
D: https://arstechnica.com */trackback/
D: https://arstechnica.com */comments/
D: https://arstechnica.com /search
D: https://arstechnica.com */*comments=
D: https://arstechnica.com */*comments-page=
D: https://arstechnica.com /services/*
D: https://arstechnica.com /civis/account/
D: https://arstechnica.com /civis/members/
D: https://arstechnica.com /civis/attachments/
D: https://arstechnica.com /civis/goto/
D: https://arstechnica.com /civis/help/
D: https://arstechnica.com /civis/posts/
D: https://arstechnica.com /civis/login/
D: https://arstechnica.com /civis/search/
D: https://arstechnica.com /civis/admin.php
D: https://arstechnica.com /civis/threads/*in_iframe=1*
D: https://arstechnica.com /civis/threads/*wp_data=*
