D: https://github.com/*/*/pulse
D: https://github.com/*/*/projects
D: https://github.com/*/*/forks
D: https://github.com/*/*/issues/new
D: https://github.com/*/*/issues/search
D: https://github.com/*/*/commits/
D: https://github.com/*/*/branches
D: https://github.com/*/*/contributors
D: https://github.com/*/*/tags
D: https://github.com/*/*/stargazers
D: https://github.com/*/*/watchers
D: https://github.com/*/*/network
D: https://github.com/*/*/graphs
D: https://github.com/*/*/compare
D: https://github.com/*/tree/
D: https://github.com/gist/
D: https://github.com/*/download
D: https://github.com/*/revisions
D: https://github.com/*/commits/*?author
D: https://github.com/*/commits/*?path
D: https://github.com/*/comments
D: https://github.com/*/archive/
D: https://github.com/*/blame/
D: https://github.com/*/raw/
D: https://github.com/*/cache/
D: https://github.com/.git/
D: https://github.com*/.git/
D: https://github.com/*.git$
D: https://github.com/search/advanced
D: https://github.com/search
D: https://github.com*/search
D: https://github.com/*q=
D: https://github.com/*.atom$
D: https://github.com/ekansa/Open-Context-Data
D: https://github.com/ekansa/opencontext-*
D: https://github.com*/tarball/
D: https://github.com*/zipball/
D: https://github.com/*source=*
D: https://github.com/*ref_cta=*
D: https://github.com/*plan=*
D: https://github.com/*return_to=*
D: https://github.com/*ref_loc=*
D: https://github.com/*setup_organization=*
D: https://github.com/*source_repo=*
D: https://github.com/*ref_page=*
D: https://github.com/*source=*
D: https://github.com/*referrer=*
D: https://github.com/*report=*
D: https://github.com/*author=*
D: https://github.com/*since=*
D: https://github.com/*until=*
D: https://github.com/*commits?author=*
D: https://github.com/*report-abuse?report=*
D: https://github.com/*tab=*
A: https://github.com/*?tab=achievements&achievement=*
D: https://github.com/account-login
D: https://github.com/Explodingstuff/
