D: https://www.booking.com*.hi.html
D: https://www.booking.com/alt_avail*
D: https://www.booking.com/fragment.*.html
D: https://www.booking.com/fragment.html
D: https://www.booking.com/fragment.*.json
D: https://www.booking.com/fragment.json
D: https://www.booking.com/_frdtcr
D: https://www.booking.com/go$
D: https://www.booking.com/go?*
D: https://www.booking.com/honing.html
D: https://www.booking.com/photo.html
D: https://www.booking.com/photo.en.html
D: https://www.booking.com/photo.de.html
D: https://www.booking.com/photo.nl.html
D: https://www.booking.com/photo.fr.html
D: https://www.booking.com/photo.es.html
D: https://www.booking.com/photo.it.html
D: https://www.booking.com/photo.pt.html
D: https://www.booking.com/photo.ja.html
D: https://www.booking.com/photo.zh.html
D: https://www.booking.com/photo.pl.html
D: https://www.booking.com/book.html
D: https://www.booking.com/mybooking.html
D: https://www.booking.com/confirmation.html
D: https://www.booking.com/reviewlist.*.html
D: https://www.booking.com/reviewlist.html
D: https://www.booking.com/srcompset.*.html
D: https://www.booking.com/srcompset.html
D: https://www.booking.com/navigation_times
D: https://www.booking.com/hotelsonmap.*.json
D: https://www.booking.com/general.*
D: https://www.booking.com/markers_on_map
D: https://www.booking.com/logo
D: https://www.booking.com/load_times
D: https://www.booking.com/anysearch.*
D: https://www.booking.com/region_attractions
D: https://www.booking.com/*city_bookings
D: https://www.booking.com/*nofollow=1
D: https://www.booking.com/flexiproduct
D: https://www.booking.com/asapi/*
D: https://www.booking.com/js_errors
D: https://www.booking.com/js_tracking
D: https://www.booking.com/join_js_tracking
D: https://www.booking.com/sendlayoutevents
D: https://www.booking.com/squeak
D: https://www.booking.com/track
D: https://www.booking.com/episode_times
D: https://www.booking.com/event
D: https://www.booking.com/hotel_attractions
D: https://www.booking.com/gta_impression*
D: https://www.booking.com/monthly_minrates*
D: https://www.booking.com/sitembk-reviews-https-index.xml
D: https://www.booking.com/vpmlogdesktopscreensize
D: https://www.booking.com/hotel/us/the-airstream-van.*.html
D: https://www.booking.com/best-price-guarantee/index.*
D: https://www.booking.com/secure-booking/index.*
D: https://www.booking.com/get-instant-confirmation/index.*
D: https://www.booking.com/book-now-pay-later/index.*
D: https://www.booking.com/no-booking-fees/index.*
D: https://www.booking.com/we-speak-your-language/index.*
D: https://www.booking.com/deals-special-offers/index.*
D: https://www.booking.com/free-cancellation/index.*
D: https://www.booking.com/pxgo?*
D: https://www.booking.com/pxbook?*
D: https://www.booking.com/product_header.html
D: https://www.booking.com/bas/*
D: https://www.booking.com/c360_v1_track
D: https://www.booking.com/c360/v1/track
D: https://www.booking.com/log_rt_blocks_order
D: https://www.booking.com/hotel_rt_onview
A: https://www.booking.com/index.hi.*
A: https://www.booking.com/hotel/index.hi.*
A: https://www.booking.com/cars/index.hi.*
A: https://www.booking.com/flights/index.hi.*
A: https://www.booking.com/attractions/index.hi.*
A: https://www.booking.com/taxi/index.hi.*
