D: https://www.imdb.com /OnThisDay
D: https://www.imdb.com /ads/
D: https://www.imdb.com /ap/
D: https://www.imdb.com /mymovies/
D: https://www.imdb.com /r/
D: https://www.imdb.com /register
D: https://www.imdb.com /registration/
D: https://www.imdb.com /search/name-text
D: https://www.imdb.com /search/title-text
D: https://www.imdb.com /find
D: https://www.imdb.com /find$
D: https://www.imdb.com /find/
D: https://www.imdb.com /tvschedule
D: https://www.imdb.com /updates
D: https://www.imdb.com /watch/_ajax/option
D: https://www.imdb.com /_json/video/mon
D: https://www.imdb.com /_json/getAdsForMediaViewer/
D: https://www.imdb.com /list/ls*/_ajax
D: https://www.imdb.com /list/ls*/export
D: https://www.imdb.com /*/*/rg*/mediaviewer/rm*/tr
D: https://www.imdb.com /*/rg*/mediaviewer/rm*/tr
D: https://www.imdb.com /*/mediaviewer/*/tr
D: https://www.imdb.com /title/tt*/mediaviewer/rm*/tr
D: https://www.imdb.com /name/nm*/mediaviewer/rm*/tr
D: https://www.imdb.com /gallery/rg*/mediaviewer/rm*/tr
D: https://www.imdb.com /tr/
D: https://www.imdb.com /title/tt*/watchoptions
D: https://www.imdb.com /search/title/?title_type=feature,tv_movie,tv_miniseries,documentary,short,video,tv_short&release_date=,2020-12-31&lists=%21ls538187658,%21ls539867036,%21ls538186228&view=simple&sort=num_votes,asc&aft
D: https://www.imdb.com /name/nm*/filmotype/*
D: https://www.imdb.com /user/ur*/ratings
D: https://www.imdb.com /user/ur*/checkins
D: https://www.imdb.com /_json/*
