D: https://www.bbc.com/bitesize/search$
D: https://www.bbc.com/bitesize/search/
D: https://www.bbc.com/bitesize/search?
D: https://www.bbc.com/cbbc/search/
D: https://www.bbc.com/cbbc/search$
D: https://www.bbc.com/cbbc/search?
D: https://www.bbc.com/cbeebies/search/
D: https://www.bbc.com/cbeebies/search$
D: https://www.bbc.com/cbeebies/search?
D: https://www.bbc.com/chwilio/
D: https://www.bbc.com/chwilio$
D: https://www.bbc.com/chwilio?
D: https://www.bbc.com/education/blocks$
D: https://www.bbc.com/education/blocks/
D: https://www.bbc.com/newsround
D: https://www.bbc.com/search/
D: https://www.bbc.com/search$
D: https://www.bbc.com/search?
D: https://www.bbc.com/food/favourites
D: https://www.bbc.com/food/search*?*
D: https://www.bbc.com/food/recipes/search*?*
D: https://www.bbc.com/education/my$
D: https://www.bbc.com/education/my/
D: https://www.bbc.com/bitesize/my$
D: https://www.bbc.com/bitesize/my/
D: https://www.bbc.com/food/recipes/*/shopping-list
D: https://www.bbc.com/food/menus/*/shopping-list
D: https://www.bbc.com/news/0
D: https://www.bbc.com/sport/alpha/
D: https://www.bbc.com/ugc$
D: https://www.bbc.com/ugc/
D: https://www.bbc.com/ugcsupport$
D: https://www.bbc.com/ugcsupport/
D: https://www.bbc.com/userinfo/
D: https://www.bbc.com/userinfo
D: https://www.bbc.com/u5llnop$
D: https://www.bbc.com/u5llnop/
D: https://www.bbc.com/sounds/search$
D: https://www.bbc.com/sounds/search/
D: https://www.bbc.com/sounds/search?
D: https://www.bbc.com/ws/includes
D: https://www.bbc.com/radio/imda
D: https://www.bbc.com/storyworks/preview/*
D: https://www.bbc.com/rd/search$
D: https://www.bbc.com/rd/search/
D: https://www.bbc.com/rd/search?
