D: https://www.vogue.com /wp-admin/
D: https://www.vogue.com /promotions/
D: https://www.vogue.com /sweeps/
D: https://www.vogue.com /search
D: https://www.vogue.com /?s=*
D: https://www.vogue.com /social/
D: https://www.vogue.com /preview/
D: https://www.vogue.com /masthead/
D: https://www.vogue.com */print
D: https://www.vogue.com /slideshow/*-inline$
D: https://www.vogue.com /video/right_rail*
D: https://www.vogue.com /*?redirectURL=
D: https://www.vogue.com /*{{url}}
D: https://www.vogue.com /*%7B%7Burl%7D%7D
D: https://www.vogue.com /auth/*
D: https://www.vogue.com /account/*
D: https://www.vogue.com /*{{section}}
D: https://www.vogue.com /*%7B%7Bsection%7D%7D
D: https://www.vogue.com /product/
D: https://www.vogue.com /services.min.js?_=
D: https://www.vogue.com /user-context?referrer
D: https://www.vogue.com /shopping/*?*+
D: https://www.vogue.com /shopping/*sort=
D: https://www.vogue.com /shopping/*?query=
D: https://www.vogue.com /shopping/*?
