D: https://www.wired.com/*?redirectURL=
D: https://www.wired.com/*/amp
D: https://www.wired.com/cgi-bin/
D: https://www.wired.com/user/
D: https://www.wired.com/templatedata/
D: https://www.wired.com/partnerfeeds/
D: https://www.wired.com/magazine/polls/
D: https://www.wired.com/services/emailFriend
D: https://www.wired.com/politics/law/news/2001/12/48946
D: https://www.wired.com/politics/law/news/2001/12/49013
D: https://www.wired.com/politics/law/news/2001/12/49083
D: https://www.wired.com/politics/law/news/2001/12/49141
D: https://www.wired.com/politics/law/news/2002/03/51042
D: https://www.wired.com/politics/law/news/2001/12/48938
D: https://www.wired.com/politics/law/news/2001/12/48940
D: https://www.wired.com/politics/law/news/2001/12/48943
D: https://www.wired.com/politics/law/news/2001/12/49013
D: https://www.wired.com/politics/law/news/2001/12/48929
D: https://www.wired.com/politics/law/news/2001/12/48938
D: https://www.wired.com/politics/law/news/2001/12/48940
D: https://www.wired.com/politics/law/news/2001/12/48941
D: https://www.wired.com/politics/law/news/2001/12/48942
D: https://www.wired.com/politics/law/news/2001/12/48943
D: https://www.wired.com/news/politics/0,1283,48946,00.html
D: https://www.wired.com/news/politics/0,1283,49132,00.html
D: https://www.wired.com/news/politics/0,48940-0.html
D: https://www.wired.com/news/politics/1,49013-0.html
D: https://www.wired.com/culture/lifestyle/news/2001/07/45247
D: https://www.wired.com/culture/lifestyle/news/2001/02/41846
D: https://www.wired.com/2001/07/dying-for-attention/
D: https://www.wired.com/wp-admin/
D: https://www.wired.com/wp-includes/
D: https://www.wired.com/wp-content/plugins/
D: https://www.wired.com/wp-content/cache/
D: https://www.wired.com/wp-content/themes/
D: https://www.wired.com/search
D: https://www.wired.com/culture/lifestyle/news/2001/08/46315
D: https://www.wired.com/2001/08/gruesome-movie-sparks-outrage/
D: https://www.wired.com/techbiz/media/news/2001/09/46556
D: https://www.wired.com/2001/09/controversial-shock-site-for-sale/
D: https://www.wired.com/2007/07/fbi-spyware-how/
D: https://www.wired.com/partners/
D: https://www.wired.com/sponsored/
D: https://www.wired.com/video/right_rail*
D: https://www.wired.com/auth/*
D: https://www.wired.com/account/*
D: https://www.wired.com/preview/
A: https://www.wired.com/wp-content/
A: https://www.wired.com/wp-content/themes/Phoenix/assets/css/style.css
A: https://www.wired.com/wp-content/themes/Phoenix/assets/css/hf.css
A: https://www.wired.com/wp-content/themes/Phoenix/assets/images/apple-touch-icon.png
A: https://www.wired.com/wp-content/themes/Phoenix/assets/images/
A: https://www.wired.com/wp-content/themes/wired/assets/images/gallery-cam@2x.png
A: https://www.wired.com/wp-content/themes/wired/assets/images/subscribe_290x110.gif
A: https://www.wired.com/wp-content/themes/wired/assets/images/wired_insider_1118_1000x190.jpg
A: https://www.wired.com/wp-content/themes/wired/assets/images/subscribe_1000x190.gif
A: https://www.wired.com/wp-content/themes/wired/assets/images/post_wired_logo_150x60.gif
A: https://www.wired.com/wp-content/themes/wired/assets/images/wired_video_1000x190.jpg
A: https://www.wired.com/wp-content/themes/wired/assets/images/subscribe_310x80.gif
A: https://www.wired.com/wp-content/themes/wired/assets/images/disruptive_by_design_2012.gif
A: https://www.wired.com/wp-content/themes/wired/assets/images/gallery-illo@2x.png
A: https://www.wired.com/wp-content/themes/Phoenix/assets/js/vendor/picturefill.min.js
A: https://www.wired.com/wp-content/themes/Phoenix/assets/images/apple-touch-icon.png
A: https://www.wired.com/wp-content/themes/Phoenix/assets/images/nav-icons-dist/sprite-2-25.png
A: https://www.wired.com/wp-content/themes/Phoenix/assets/images/rad-fallback/fallback-short.jpg
A: https://www.wired.com/wp-content/themes/Phoenix/assets/images/rad-fallback/fallback-tall-b.jpg
A: https://www.wired.com/wp-includes/js/wp-emoji-release.min.js
A: https://www.wired.com/wp-includes/js/wp-emoji-release.min.js?ver=4.5.2
A: https://www.wired.com/wp-content/themes/Phoenix/assets/css/cyphon.css
A: https://www.wired.com/wp-content/plugins/feature-story-builder/builder-frontend/assets/css/fsb.css
A: https://www.wired.com/wp-includes/js/mediaelement/mediaelementplayer.min.css
A: https://www.wired.com/wp-includes/js/mediaelement/wp-mediaelement.min.css
A: https://www.wired.com/wp-content/themes/Phoenix/assets/css/exchange.css
A: https://www.wired.com/wp-content/themes/Phoenix/assets/css/wired-blank-canvas.css
A: https://www.wired.com/wp-content/plugins/google-to-table/css/google-to-table.css
A: https://www.wired.com/wp-content/plugins/feature-story-builder/builder-frontend/assets/images/arrow.png
A: https://www.wired.com/wp-content/plugins/feature-story-builder/builder-frontend/assets/images/footer-wired.png
A: https://www.wired.com/wp-content/plugins/feature-story-builder/builder-frontend/assets/images/logo-w.png
A: https://www.wired.com/wp-content/plugins/feature-story-builder/builder-frontend/assets/images/w.png
A: https://www.wired.com/wp-includes/js/mediaelement/mediaelementplayer.min.css
A: https://www.wired.com/wp-includes/js/mediaelement/wp-mediaelement.min.css
A: https://www.wired.com/partners/bnymellon/futureofmoney/images
D: https://www.wired.com/*{{url}}
D: https://www.wired.com/*%7B%7Burl%7D%7D
D: https://www.wired.com/*{{section}}
D: https://www.wired.com/*%7B%7Bsection%7D%7D
D: https://www.wired.com/product/
D: https://www.wired.com/user-context?referrer
D: https://www.wired.com/services.min.js?_=
