D: https://www.amazon.com/exec/obidos/account-access-login
D: https://www.amazon.com/exec/obidos/change-style
D: https://www.amazon.com/exec/obidos/flex-sign-in
D: https://www.amazon.com/exec/obidos/handle-buy-box
D: https://www.amazon.com/exec/obidos/tg/cm/member/
D: https://www.amazon.com/gp/aw/help/id=sss
D: https://www.amazon.com/gp/cart
D: https://www.amazon.com/gp/flex
D: https://www.amazon.com/gp/product/e-mail-friend
D: https://www.amazon.com/gp/product/product-availability
D: https://www.amazon.com/gp/product/rate-this-item
D: https://www.amazon.com/gp/sign-in
D: https://www.amazon.com/gp/reader
D: https://www.amazon.com/gp/sitbv3/reader
D: https://www.amazon.com/gp/richpub/syltguides/create
D: https://www.amazon.com/gp/gfix
D: https://www.amazon.com/gp/associations/wizard.html
D: https://www.amazon.com/gp/dmusic/order
D: https://www.amazon.com/gp/legacy-handle-buy-box.html
D: https://www.amazon.com/gp/aws/ssop
D: https://www.amazon.com/gp/yourstore
D: https://www.amazon.com/gp/gift-central/organizer/add-wishlist
D: https://www.amazon.com/gp/vote
D: https://www.amazon.com/gp/voting/
D: https://www.amazon.com/gp/music/wma-pop-up
D: https://www.amazon.com/gp/customer-images
D: https://www.amazon.com/gp/richpub/listmania/createpipeline
D: https://www.amazon.com/gp/content-form
D: https://www.amazon.com/gp/pdp/invitation/invite
D: https://www.amazon.com/gp/customer-reviews/common/du
D: https://www.amazon.com/gp/customer-reviews/write-a-review.html
D: https://www.amazon.com/gp/associations/wizard.html
D: https://www.amazon.com/gp/music/clipserve
D: https://www.amazon.com/gp/customer-media/upload
D: https://www.amazon.com/gp/history
D: https://www.amazon.com/gp/item-dispatch
D: https://www.amazon.com/gp/dmusic/order/handle-buy-box.html
D: https://www.amazon.com/gp/recsradio
D: https://www.amazon.com/gp/slredirect
D: https://www.amazon.com/dp/shipping/
D: https://www.amazon.com/dp/twister-update/
D: https://www.amazon.com/dp/manual-submit/
D: https://www.amazon.com/dp/e-mail-friend/
D: https://www.amazon.com/dp/product-availability/
D: https://www.amazon.com/dp/rate-this-item/
D: https://www.amazon.com/gp/registry/wishlist/*/reserve
D: https://www.amazon.com/gp/structured-ratings/actions/get-experience.html
D: https://www.amazon.com/gp/twitter/
D: https://www.amazon.com/ap/signin
D: https://www.amazon.com/gp/registry/wishlist/
D: https://www.amazon.com/wishlist/
A: https://www.amazon.com/wishlist/universal*
A: https://www.amazon.com/wishlist/vendor-button*
A: https://www.amazon.com/wishlist/get-button*
D: https://www.amazon.com/gp/wishlist/
A: https://www.amazon.com/gp/wishlist/universal*
A: https://www.amazon.com/gp/wishlist/vendor-button*
A: https://www.amazon.com/gp/wishlist/ipad-install*
D: https://www.amazon.com/registry/wishlist/
D: https://www.amazon.com/review/common/du
D: https://www.amazon.com/gp/registry/search.html
D: https://www.amazon.com/product-reviews/B0069IY63Y
D: https://www.amazon.com/gp/orc/rml/
D: https://www.amazon.com*/gcrnsts
D: https://www.amazon.com/gp/gc/widget
D: https://www.amazon.com/gp/dmusic/mp3/player
D: https://www.amazon.com/gp/entity-alert/external
D: https://www.amazon.com/gp/customer-reviews/dynamic/sims-box
D: https://www.amazon.com/review/dynamic/sims-box
D: https://www.amazon.com/gp/redirect.html
D: https://www.amazon.com/gp/twister/ajaxv2
D: https://www.amazon.com/ss/twister/ajax
D: https://www.amazon.com/b?*node=7454917011
D: https://www.amazon.com/b?*node=7454927011
D: https://www.amazon.com/b?*node=7454939011
D: https://www.amazon.com/b?*node=7454898011
D: https://www.amazon.com/gp/customer-media/actions/delete/
D: https://www.amazon.com/gp/customer-media/actions/edit-caption/
D: https://www.amazon.com/gp/dmusic/
A: https://www.amazon.com/gp/dmusic/promotions/PrimeMusic
A: https://www.amazon.com/gp/dmusic/promotions/AmazonMusicUnlimited
D: https://www.amazon.com/gp/offer-listing/
D: https://www.amazon.com/b?*node=9052533011
D: https://www.amazon.com/lm/R1XIHQVKXSKBNJ
D: https://www.amazon.com/lm/R3HQ5WJSZK6QSO
D: https://www.amazon.com/surprise/
D: https://www.amazon.com/local/ajax/
D: https://www.amazon.com*/B00M3E1NYI
D: https://www.amazon.com*/B00M3E1Q5Y
D: https://www.amazon.com*/B00M3E1TOM
D: https://www.amazon.com*/B00M3E1WYO
D: https://www.amazon.com*/B00M3E204K
D: https://www.amazon.com*/B00M3E236A
D: https://www.amazon.com*/B00M3E260I
D: https://www.amazon.com*/B00M3E28WO
D: https://www.amazon.com*/B00M3E2BC6
D: https://www.amazon.com*/B00M3E2DPQ
D: https://www.amazon.com*/B00M3E2GU8
D: https://www.amazon.com*/B00M3E2J14
D: https://www.amazon.com*/B00M3E2LOE
D: https://www.amazon.com*/B00M3E1HJY
D: https://www.amazon.com/gp/socialmedia/giveaways
D: https://www.amazon.com/gp/b2b-rd
D: https://www.amazon.com/gp/aw/so.html
D: https://www.amazon.com/reviews/iframe
D: https://www.amazon.com/gp/switch-language
D: https://www.amazon.com/ga/p/
D: https://www.amazon.com/gp/profile/
D: https://www.amazon.com/giveaway/host/setup/
D: https://www.amazon.com/ss/customer-reviews/lighthouse/
D: https://www.amazon.com/ospublishing/story/*
D: https://www.amazon.com/gp/aw/ol/
D: https://www.amazon.com/gp/promotion/
D: https://www.amazon.com/hz/leaderboard/top-reviewers/
D: https://www.amazon.com/creatorhub
D: https://www.amazon.com/creatorhub/*
D: https://www.amazon.com/slp/s$
D: https://www.amazon.com/-/
A: https://www.amazon.com/-/es/
A: https://www.amazon.com/-/en$
A: https://www.amazon.com/-/zh_TW/
A: https://www.amazon.com/-/zh_TW$
A: https://www.amazon.com/-/he/
A: https://www.amazon.com/-/he$
D: https://www.amazon.com/hz/help/contact/*/message/$
D: https://www.amazon.com/gp/aw/shoppingAids/
D: https://www.amazon.com/rss/people/*/reviews
D: https://www.amazon.com/gp/pdp/rss/*/reviews
D: https://www.amazon.com/gp/cdp/member-reviews/
D: https://www.amazon.com/gp/aw/cr/
D: https://www.amazon.com*/sim/B001132UEE
A: https://www.amazon.com/gp/offer-listing/B000
A: https://www.amazon.com/gp/offer-listing/9000
D: https://www.amazon.com/gp/aag
A: https://www.amazon.com/gp/aag/main?*seller=ABVFEJU8LS620
D: https://www.amazon.com/gp/pdp/profile/
D: https://www.amazon.com/gp/help/customer/express/c2c/
D: https://www.amazon.com/slp/*/b$
D: https://www.amazon.com/hz/contact-us/ajax/initiate-trusted-contact/
D: https://www.amazon.com/hp/video/
D: https://www.amazon.com/gp/video/api
D: https://www.amazon.com/gp/video/settings
D: https://www.amazon.com/gp/video/library
D: https://www.amazon.com/gp/video/watchlist
D: https://www.amazon.com/gp/video/mystuff
D: https://www.amazon.com/gp/video/profiles
D: https://www.amazon.com/gp/video/search
D: https://www.amazon.com/gp/video/auth
D: https://www.amazon.com/gp/video/salp/i
